# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
#  - osx
  - linux
#  - windows

r:
- 3.2
- 3.3
- oldrel
- release
- devel

matrix:
  allow_failures:
  - r:
    - devel
    - 3.2
    - 3.3

after_success:
  - Rscript -e 'covr::codecov()'
